# Generated by Django 2.2 on 2019-07-11 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190308_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'medium', 'verbose_name_plural': 'media'},
        ),
        migrations.AlterField(
            model_name='media',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='news.Article'),
        ),
    ]
