# Generated by Django 2.2.5 on 2019-09-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190711_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ImageField(upload_to='news_media'),
        ),
    ]
