# Generated by Django 2.1.4 on 2019-02-04 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icategory',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
