# Generated by Django 2.1.3 on 2018-11-28 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20181128_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='user_id',
        ),
    ]
