# Generated by Django 2.1.3 on 2018-11-26 01:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20181121_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_ans',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Question'),
        ),
    ]
