# Generated by Django 2.1.3 on 2018-11-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20181126_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='right_answer',
            field=models.CharField(default='none', max_length=70),
            preserve_default=False,
        ),
    ]
