# Generated by Django 2.1.3 on 2018-11-29 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_quiz_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quiz_id',
            new_name='quiz',
        ),
    ]
