# Generated by Django 2.1.5 on 2019-02-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20190211_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_num_for_student',
        ),
    ]
