# Generated by Django 2.1.5 on 2019-02-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_carouselindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselindex',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
