# Generated by Django 2.1.5 on 2019-03-07 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_auto_20190228_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselindex',
            options={'verbose_name': 'carousel index', 'verbose_name_plural': 'carousel indices'},
        ),
    ]
